/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            val groovy = version("groovy", "3.0.21")
            library("groovy-core", "org.codehaus.groovy", "groovy").versionRef(groovy)
            library("groovy-json", "org.codehaus.groovy", "groovy-json").versionRef(groovy)
            library("groovy-nio", "org.codehaus.groovy", "groovy-nio").versionRef(groovy)
            bundle("groovy", listOf("groovy-core", "groovy-json", "groovy-nio"))
            val jooq = version("groovy", "3.19.8")
            library("jooq", "org.jooq", "jooq").versionRef(jooq)
            library("jooq-meta", "org.jooq", "jooq-meta").versionRef(jooq)
            library("jooq-ext", "org.jooq", "jooq-meta-extensions").versionRef(jooq)
            bundle("jooq-bundle", listOf("jooq", "jooq-meta", "jooq-ext"))
            library("jooq-liquibase", "org.jooq", "jooq-meta-extensions-liquibase").versionRef(jooq)

            plugin("download", "de.undercouch.download").version("5.6.0")
            plugin("testLogger", "com.adarshr.test-logger").version("4.0.0")
            plugin("jooq", "org.jooq:jooq-codegen-gradle").versionRef(jooq)

        }
    }
}

rootProject.name = "marine"
include("shared", "wire", "test", "synthetic", "geo", "loader", "vessel", "tracker", "config", "alert")